### ISSUE TITLE
macのdmg packageを起動できない

### ISSUE THREAD

**Issue by ikazoy** [ihiroky/live-comment#40]
# 手順

```
cd live-comment
yarn install
yarn --cwd packages/screen build
cd packages/desktop
yarn install
yarn package:mac
```
生成された`packages/desktop/dist/live-comment-0.1.0.dmg` を~/Applicationに移動して実行すると以下のエラーが発生

```
Uncaught Exception:
Error: The 'screen' module can't be used before the app 'ready' event
at Object.s.<computed> [as getCursorScreenPoint] (electron/js2c/browser_init.js:241:262)
at getWorkArea (/Applications/live-comment.app/Contents/Resources/app.asar/dist/js/index.js:20:51)
at showMainWindow (/Applications/live-comment.app/Contents/Resources/app.asar/dist/js/index.js:128:22)
at App.<anonymous> (/Applications/live-comment.app/Contents/Resources/app.asar/dist/js/index.js:178:9)
at App.emit (events.js:223:5)
```

![image](https://user-images.githubusercontent.com/385109/114823647-c65a6900-9dfe-11eb-9495-2879128e98ac.png)

**Comment by ihiroky** [comment]
https://github.com/ihiroky/live-comment/pull/44

確認環境構築してから再確認

**Comment by ihiroky** [comment]
- 実行時ディレクトリの調整する
https://github.com/ihiroky/live-comment/pull/57

- activate イベントでウィンドウを構築するときは ready イベントが発生した後のみに限る
https://github.com/ihiroky/live-comment/pull/44

- Mac固有イベントハンドリングを追加する
https://github.com/ihiroky/live-comment/pull/37
